version: "3.9"
services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=spacecarsinc
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    container_name: mysqldatabase
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    ports:
      - "80:80"
    depends_on:
      - database
    restart: "no"
